### PR TITLE
Use LESS files to build CSS

### PR DESCRIPTION
**Pull request by icaliman**
Added possibility to build CSS from LESS files.

You can use this by adding LESS code into: `lib/modules/apostrophe-palette-global/styles/index.less`

```less
@import "other-less-file";

// default value will be changed from palette fields
@color-background: #ff3f00;

body {
  background-color: @color-background;
}
```

Configure `apostrophe-palette-global` module in `app.js` or `lib/modules/apostrophe-palette-global/index.js`:
```js
...
'apostrophe-palette-global': {
    less: true, // Using LESS files

    paletteFields: [ // array of fields, like a normal schema
        {
            name: 'color-background',
            label: 'Background color',
            type: 'color',
        }
    ]
}
...
```

### CODE REVIEW

**Review by boutell — COMMENTED** [review]
Hmm. It's not clear to me how the LESS support being pushed to this module helps. LESS is already supported in Apostrophe's regular asset pushing system.

**Comment by icaliman** [comment]
In huge themes it can be a lot of work to add `selector`, `property`, `mediaQuery`, `valueTemplate`, `unit` for each CSS property.

It can be easier to create a file with LESS code for such a theme.

**Comment by icaliman** [comment]
@boutell with LESS support it can be easier to modify all theme styles with palette.

**Comment by ToshKoevoets** [comment]
@boutell in apos2 it was possible to import .less files. In the new version it seems only scss is automatically loaded according to the docs: https://v3.docs.apostrophecms.org/guide/front-end-assets.html

Is it possible to also makes this work with less files?

**Comment by boutell** [comment]
This PR concerned the A2 version of the apostrophe-palette module only. This is not the right repo for a question about LESS support in A3, but I can give a response here.

We chose to support SASS in A3 because the majority of projects have migrated to SASS. Bootstrap is the most notable example. This reflects a general choice by the developer community to go with SASS. Apostrophe intentionally includes a simple built-in webpack build for straightforward use cases, but we have also made it extensible, so if you really prefer SASS it is possible to enable it:

https://v3.docs.apostrophecms.org/guide/webpack.html

As for this pull request, apologies for the original contributor for dropping the ball on that conversation as the A3 migration process got rolling. At this late date we won't be adding LESS support to apostrophe-palette for A2. In general configuring palette to drive CSS variables rather than specific CSS properties is just about as effective and requires no compilation. For that reason we haven't added SASS support to the A3 version of palette so far either.

**Pull request closed without merging**
